Меняй-удаляй
htmlacademy-ecmascript/2483435-big-trip-23 pull request #12
Opened 2024-05-22 15:25 UTC by b-trots

1. Добавил отслеживание именений модели.
2. Добавил презентер для фильтров.
3. Подключил фильтры.
4. Подключил отрисовку о пустом списке.

---
:mortar_board: [Меняй-удаляй](https://up.htmlacademy.ru/ecmascript/23/user/2483435/tasks/15)

2024-05-25 07:24 UTC, b-trots commented
![image](https://github.com/htmlacademy-ecmascript/2483435-big-trip-23/assets/159007823/d5657a13-48c1-4513-a183-f4082473a9da)

Не могу найти кнопку ready for review

2024-05-25 08:49 UTC, baileys-li commented
@b-trots она есть только если ПР в статусе draft

2024-05-25 11:07 UTC, baileys-li requested changes
Нужно доделать сохранение цены

2024-05-27 05:04 UTC, baileys-li approved these changes

2024-05-27 05:04 UTC, baileys-li commented on src/const.ts
>  }
У вас есть критерий на нейминг енамов (ключи в ВЕРХНЕМ регистре_

2024-05-27 05:04 UTC, merged