Module2 task1
htmlacademy-ecmascript/2483435-big-trip-23 pull request #4
Opened 2024-04-28 05:22 UTC by b-trots

2024-04-28 07:54 UTC, baileys-li requested changes
Eslint ошибки

2024-04-29 09:43 UTC, baileys-li commented
@b-trots привет, а ты будешь ещё пушить в эту ветку?

2024-04-29 09:52 UTC, b-trots commented
Да, буду пушить в эту ветку

2024-04-30 22:44 UTC, b-trots commented
Вроде разобрался, как конструкторы работают, и что зачем нужно. 
В этот пулреквест больше не буду пушить.

Понял, зачем типизация. Штука обалденная. Но не совсем ещё понимаю, где её прописывать и как применять - во многих местах просто "any" поставил пока.

2024-05-01 06:25 UTC, baileys-li approved these changes

2024-05-01 06:25 UTC, baileys-li commented on src/types/way-point.ts
> +  destination: object[];
Это не то, что будет возвращаться с сервера. Надо будет обсудить сегодня этот контракт

2024-05-01 06:25 UTC, baileys-li commented
Вот это ты разбил вьюхи :)

2024-05-01 06:27 UTC, merged